# Generated by Django 5.2.17 on 2026-08-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuarioforo_seguidos_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioforo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
