# Generated by Django 5.2.17 on 2026-08-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuarioforo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioforo',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
