# Generated by Django 5.2.17 on 2026-08-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_mensaje_imagen_alter_mensaje_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['remitente', 'destinatario'], name='usuarios_me_remiten_a10a8a_idx'),
        ),
    ]
