# Generated by Django 5.2.17 on 2026-09-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_mensaje_fecha_envio_alter_mensaje_leido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='chat_imagenes/'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='chat_imagenes/'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='chat_imagenes/'),
        ),
    ]
