# Generated by Django 5.2.17 on 2026-09-20 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_mensaje_imagen2_mensaje_imagen3_mensaje_imagen4'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='mensaje_respondido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='usuarios.mensaje'),
        ),
    ]
