# Generated by Django 5.2.17 on 2026-09-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_mensaje_mensaje_respondido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioforo',
            name='codigo_recuperacion_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
