# Generated by Django 5.2.17 on 2026-09-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuarioforo_codigo_recuperacion_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioforo',
            name='acepto_terminos_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuarioforo',
            name='acepto_terminos_version',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
