# Generated by Django 5.2.17 on 2026-09-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_usuarioforo_acepto_terminos_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioforo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuarioforo',
            name='reset_password_codigo_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usuarioforo',
            name='reset_password_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuarioforo',
            name='reset_password_intentos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
