# Generated by Django 5.2.17 on 2026-09-29 03:25

from django.db import migrations, models


def emails_vacios_a_null(apps, schema_editor):
    # email es unique+null: '' solo lo puede tener una cuenta, NULL todas las que quieran.
    UsuarioForo = apps.get_model('usuarios', 'UsuarioForo')
    UsuarioForo.objects.filter(email='').update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_usuarioforo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioforo',
            name='email_codigo_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuarioforo',
            name='email_codigo_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usuarioforo',
            name='email_codigo_intentos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuarioforo',
            name='email_pendiente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usuarioforo',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.RunPython(emails_vacios_a_null, migrations.RunPython.noop),
    ]
