# Generated by Django 5.2.17 on 2026-09-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_verificacion_email'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mensaje',
            name='usuarios_me_remiten_a10a8a_idx',
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['remitente', 'destinatario', '-fecha_envio'], name='mensaje_conversacion'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(condition=models.Q(('leido', False)), fields=['destinatario'], name='mensaje_no_leidos'),
        ),
    ]
