# Generated by Django 5.2.17 on 2026-08-26 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_hilo_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='respuestas_likeadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
