# Generated by Django 5.2.17 on 2026-08-26 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0003_respuesta_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='respuesta_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_hijas', to='foro.respuesta'),
        ),
    ]
