# Generated by Django 5.2.17 on 2026-08-30 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0004_respuesta_respuesta_padre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('like_hilo', 'Like a hilo'), ('comentario', 'Comentario'), ('like_respuesta', 'Like a respuesta'), ('seguidor', 'Nuevo seguidor')], max_length=20)),
                ('leido', models.BooleanField(db_index=True, default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True, db_index=True)),
                ('actores', models.ManyToManyField(blank=True, related_name='notificaciones_generadas', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('hilo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foro.hilo')),
                ('respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foro.respuesta')),
            ],
            options={
                'ordering': ['-ultima_actividad'],
                'indexes': [models.Index(fields=['destinatario', 'leido'], name='foro_notifi_destina_f9e751_idx')],
            },
        ),
    ]
