# Generated by Django 5.2.17 on 2026-08-31 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0006_sugerencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='sugerencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foro.sugerencia'),
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='sugerencias_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='sugerencias_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('like_hilo', 'Like a hilo'), ('comentario', 'Comentario'), ('like_respuesta', 'Like a respuesta'), ('seguidor', 'Nuevo seguidor'), ('like_sug', 'Like a sugerencia'), ('coment_sug', 'Comentario en sugerencia')], max_length=25),
        ),
        migrations.CreateModel(
            name='RespuestaSugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sugerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='foro.sugerencia')),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
