# Generated by Django 5.2.17 on 2026-08-31 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0007_notificacion_sugerencia_sugerencia_dislikes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestasugerencia',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='respuestas_sugerencia_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestasugerencia',
            name='respuesta_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_hijas', to='foro.respuestasugerencia'),
        ),
    ]
