# Generated by Django 5.2.17 on 2026-09-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0009_notificacion_respuesta_sugerencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hilo',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='hilos/imagenes/'),
        ),
        migrations.AddField(
            model_name='hilo',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='hilos/imagenes/'),
        ),
        migrations.AddField(
            model_name='hilo',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='hilos/imagenes/'),
        ),
    ]
