# Generated by Django 5.2.17 on 2026-09-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0010_hilo_imagen2_hilo_imagen3_hilo_imagen4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hilo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='respuestasugerencia',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
