# Generated by Django 5.2.17 on 2026-09-07 15:00

import uuid
from django.db import migrations, models

def generar_uuids(apps, schema_editor):
    Hilo = apps.get_model('foro', 'Hilo')
    for hilo in Hilo.objects.all():
        hilo.public_id = uuid.uuid4()
        hilo.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0011_alter_hilo_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hilo',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(generar_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='hilo',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]