# Generated by Django 5.2.17 on 2026-09-07 15:29

import uuid
from django.db import migrations, models

def generar_uuids_respuesta(apps, schema_editor):
    Respuesta = apps.get_model('foro', 'Respuesta')
    for respuesta in Respuesta.objects.all():
        respuesta.public_id = uuid.uuid4()
        respuesta.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0012_hilo_public_id'),
    ]

    operations = [
        # 1. Agregamos el campo permitiendo nulos temporalmente
        migrations.AddField(
            model_name='respuesta',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # 2. Generamos un UUID único para cada respuesta ya existente
        migrations.RunPython(generar_uuids_respuesta, migrations.RunPython.noop),
        # 3. Alteramos el campo para aplicar unique=True
        migrations.AlterField(
            model_name='respuesta',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        # 4. Se mantiene el ajuste del índice que Django detectó en Hilo
        migrations.AlterField(
            model_name='hilo',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]