# Generated by Django 5.2.17 on 2026-09-07 15:47

import uuid
from django.db import migrations, models

def generar_uuids_sugerencia(apps, schema_editor):
    Sugerencia = apps.get_model('foro', 'Sugerencia')
    for sug in Sugerencia.objects.all():
        sug.public_id = uuid.uuid4()
        sug.save(update_fields=['public_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0013_respuesta_public_id_alter_hilo_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencia',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(generar_uuids_sugerencia, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sugerencia',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]