# Generated by Django 5.2.17 on 2026-09-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0014_sugerencia_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hilo',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hilo',
            name='respuestas_count',
            field=models.IntegerField(default=0),
        ),
    ]
