# Generated by Django 5.2.17 on 2026-09-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0015_hilo_likes_count_hilo_respuestas_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hilo',
            name='contenido',
            field=models.TextField(max_length=500),
        ),
    ]
