# Generated by Django 5.2.17 on 2026-09-24 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0016_alter_hilo_contenido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField(help_text='Texto corto del aviso')),
                ('tipo', models.CharField(choices=[('info', 'Información (Azul)'), ('feature', 'Nueva Función (Morado)'), ('alert', 'Mantenimiento / Urgente (Rojo)')], default='info', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Desmárcalo para apagar el aviso a nivel global')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('visto_por', models.ManyToManyField(blank=True, related_name='avisos_vistos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aviso Global',
                'verbose_name_plural': 'Avisos Globales',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
