# Generated by Django 5.2.17 on 2026-09-24 22:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0017_avisoglobal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hilo',
            name='ultima_actividad',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
