# Generated by Django 5.2.17 on 2026-09-29 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0019_hilo_reportes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hilo',
            name='respuestas_count',
        ),
    ]
