# Generated by Django 5.2.17 on 2026-09-29 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0021_seguridad_supabase'),
        ('usuarios', '0014_indices_rendimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hilo',
            index=models.Index(condition=models.Q(('activo', True)), fields=['universidad', '-id'], name='hilo_uni_recientes'),
        ),
    ]
